from __future__ import annotations

from collections.abc import Sequence
from typing import Any

import jax
import jax.numpy as jnp

from sender_marl.core.distributions import (
    deterministic_squashed_action,
    sample_squashed_gaussian,
    squashed_gaussian_log_prob_from_pre_tanh,
)
from sender_marl.off_policy.sac_state import (
    SACConfig,
    SACLearnerState,
    SACUpdateOutput,
)
from sender_marl.off_policy.types import SACBatch


Array = jax.Array


def _polyak_update(new_params: Any, target_params: Any, tau: float) -> Any:
    return jax.tree_util.tree_map(
        lambda new, target: tau * new + (1.0 - tau) * target,
        new_params,
        target_params,
    )


def _sample_joint_actions(
    key: Array,
    actor_apply_fn,
    actor_params_by_agent: Sequence[Any],
    observations: Array,
) -> tuple[Array, Array]:
    """Sample all frozen actor snapshots on a joint observation batch."""

    num_agents = len(actor_params_by_agent)
    keys = jax.random.split(key, num_agents)
    actions = []
    log_probs = []
    for agent_id in range(num_agents):
        mean_i, log_std_i = actor_apply_fn(
            {"params": actor_params_by_agent[agent_id]},
            observations[:, agent_id, :],
        )
        sample_i = sample_squashed_gaussian(keys[agent_id], mean_i, log_std_i)
        actions.append(jax.lax.stop_gradient(sample_i.action))
        log_probs.append(jax.lax.stop_gradient(sample_i.log_prob))
    return jnp.stack(actions, axis=1), jnp.stack(log_probs, axis=1)


def _deterministic_joint_actions(
    actor_apply_fn,
    actor_params_by_agent: Sequence[Any],
    observations: Array,
) -> tuple[Array, Array]:
    """Evaluate frozen actors deterministically for fixed-batch diagnostics."""

    actions = []
    log_probs = []
    for agent_id, actor_params in enumerate(actor_params_by_agent):
        mean_i, log_std_i = actor_apply_fn(
            {"params": actor_params},
            observations[:, agent_id, :],
        )
        actions.append(
            jax.lax.stop_gradient(deterministic_squashed_action(mean_i))
        )
        log_probs.append(
            jax.lax.stop_gradient(
                squashed_gaussian_log_prob_from_pre_tanh(
                    mean_i, mean_i, log_std_i
                )
            )
        )
    return jnp.stack(actions, axis=1), jnp.stack(log_probs, axis=1)


def make_sac_update(
    config: SACConfig,
    *,
    agent_id: int,
    num_agents: int,
    jit: bool = True,
):
    """Build one focal-agent SAC update with a private centralized critic.

    The critic and target critic are updated on every call. The focal actor and
    its entropy temperature are updated only when ``update_actor`` is true.
    Opponent actions always come from a frozen snapshot tuple supplied by the
    caller, so no gradient can cross into another agent's actor.
    """

    if not 0 <= agent_id < num_agents:
        raise ValueError(
            f"agent_id must be in [0, {num_agents}), got {agent_id}."
        )

    def update(
        key: Array,
        learner_state: SACLearnerState,
        batch: SACBatch,
        actor_params_by_agent: Sequence[Any],
        update_actor: Array,
    ) -> SACUpdateOutput:
        if len(actor_params_by_agent) != num_agents:
            raise ValueError("Incorrect number of actor snapshots.")

        do_actor_update = jnp.asarray(update_actor, dtype=jnp.bool_)
        target_key, opponent_key, actor_key, alpha_key = jax.random.split(
            key, 4
        )
        alpha_before = jnp.exp(
            learner_state.alpha_state.params["log_alpha"]
        )

        # Bellman target: all next actions are generated by the synchronized,
        # frozen actor snapshot tuple. Only the focal agent's entropy is added.
        next_joint_actions, next_log_probs = _sample_joint_actions(
            target_key,
            learner_state.actor_state.apply_fn,
            actor_params_by_agent,
            batch.next_observations,
        )
        target_q1, target_q2 = learner_state.critic_state.apply_fn(
            {"params": learner_state.target_critic_params},
            batch.next_model_states,
            next_joint_actions,
        )
        focal_next_log_prob = next_log_probs[:, agent_id]
        target_soft_value = (
            jnp.minimum(target_q1, target_q2)
            - jax.lax.stop_gradient(alpha_before) * focal_next_log_prob
        )
        td_target = batch.rewards + (
            config.gamma * (1.0 - batch.dones) * target_soft_value
        )
        td_target = jax.lax.stop_gradient(td_target)

        def critic_loss_fn(critic_params):
            q1, q2 = learner_state.critic_state.apply_fn(
                {"params": critic_params},
                batch.model_states,
                batch.actions,
            )
            q1_error = q1 - td_target
            q2_error = q2 - td_target
            q1_loss = jnp.mean(jnp.square(q1_error))
            q2_loss = jnp.mean(jnp.square(q2_error))
            return q1_loss + q2_loss, {
                "q1_loss": q1_loss,
                "q2_loss": q2_loss,
                "q1_mean": jnp.mean(q1),
                "q2_mean": jnp.mean(q2),
                "target_q_mean": jnp.mean(td_target),
                "td_abs_mean": 0.5 * (
                    jnp.mean(jnp.abs(q1_error))
                    + jnp.mean(jnp.abs(q2_error))
                ),
            }

        (critic_loss, critic_metrics), critic_grads = jax.value_and_grad(
            critic_loss_fn, has_aux=True
        )(learner_state.critic_state.params)
        critic_state = learner_state.critic_state.apply_gradients(
            grads=critic_grads
        )

        # Opponent actions are sampled once from frozen snapshots and treated as
        # constants inside the focal actor gradient calculation.
        opponent_joint_actions, _ = _sample_joint_actions(
            opponent_key,
            learner_state.actor_state.apply_fn,
            actor_params_by_agent,
            batch.observations,
        )

        def actor_loss_fn(actor_params):
            mean, log_std = learner_state.actor_state.apply_fn(
                {"params": actor_params},
                batch.observations[:, agent_id, :],
            )
            focal_sample = sample_squashed_gaussian(
                actor_key, mean, log_std
            )
            joint_actions = opponent_joint_actions.at[:, agent_id, :].set(
                focal_sample.action
            )
            q1, q2 = critic_state.apply_fn(
                {"params": critic_state.params},
                batch.model_states,
                joint_actions,
            )
            minimum_q = jnp.minimum(q1, q2)
            loss = jnp.mean(
                jax.lax.stop_gradient(alpha_before)
                * focal_sample.log_prob
                - minimum_q
            )
            return loss, {
                "policy_log_prob": jnp.mean(focal_sample.log_prob),
                "policy_entropy": -jnp.mean(focal_sample.log_prob),
                "policy_q_mean": jnp.mean(minimum_q),
                "action_abs_mean": jnp.mean(
                    jnp.abs(focal_sample.action)
                ),
                "opponent_action_abs_mean": jnp.mean(
                    jnp.abs(opponent_joint_actions)
                ),
            }

        (actor_loss, actor_metrics), actor_grads = jax.value_and_grad(
            actor_loss_fn, has_aux=True
        )(learner_state.actor_state.params)
        actor_state = jax.lax.cond(
            do_actor_update,
            lambda state: state.apply_gradients(grads=actor_grads),
            lambda state: state,
            learner_state.actor_state,
        )

        # Alpha is delayed with the actor. During critic warmup and skipped
        # policy steps, it remains exactly unchanged.
        mean_for_alpha, log_std_for_alpha = actor_state.apply_fn(
            {"params": actor_state.params},
            batch.observations[:, agent_id, :],
        )
        alpha_sample = sample_squashed_gaussian(
            alpha_key, mean_for_alpha, log_std_for_alpha
        )
        entropy_residual = jax.lax.stop_gradient(
            alpha_sample.log_prob + config.target_entropy
        )

        def alpha_loss_fn(alpha_params):
            return -jnp.mean(
                alpha_params["log_alpha"] * entropy_residual
            )

        alpha_loss, alpha_grads = jax.value_and_grad(alpha_loss_fn)(
            learner_state.alpha_state.params
        )
        alpha_state = jax.lax.cond(
            do_actor_update,
            lambda state: state.apply_gradients(grads=alpha_grads),
            lambda state: state,
            learner_state.alpha_state,
        )
        alpha = jnp.exp(alpha_state.params["log_alpha"])

        # Target critics track the critic on every critic update, including the
        # critic-only warmup phase.
        target_critic_params = _polyak_update(
            critic_state.params,
            learner_state.target_critic_params,
            config.tau,
        )
        return SACUpdateOutput(
            learner_state=SACLearnerState(
                actor_state=actor_state,
                critic_state=critic_state,
                alpha_state=alpha_state,
                target_critic_params=target_critic_params,
            ),
            metrics={
                "critic_loss": critic_loss,
                "actor_loss": actor_loss,
                "alpha_loss": alpha_loss,
                "alpha": alpha,
                "actor_update_applied": do_actor_update.astype(jnp.float32),
                **critic_metrics,
                **actor_metrics,
            },
        )

    return jax.jit(update) if jit else update


def make_fixed_batch_critic_evaluator(
    config: SACConfig,
    *,
    agent_id: int,
    num_agents: int,
    jit: bool = True,
):
    """Evaluate one learner repeatedly on a frozen replay batch.

    The batch and action-selection rule are fixed. Current actor snapshots,
    critic parameters, and target parameters are intentionally used, so this is
    a stable diagnostic of learning on the same transitions rather than a
    second training objective.
    """

    if not 0 <= agent_id < num_agents:
        raise ValueError(
            f"agent_id must be in [0, {num_agents}), got {agent_id}."
        )

    def evaluate(
        learner_state: SACLearnerState,
        batch: SACBatch,
        actor_params_by_agent: Sequence[Any],
    ) -> dict[str, Array]:
        if len(actor_params_by_agent) != num_agents:
            raise ValueError("Incorrect number of actor snapshots.")

        next_joint_actions, next_log_probs = _deterministic_joint_actions(
            learner_state.actor_state.apply_fn,
            actor_params_by_agent,
            batch.next_observations,
        )
        target_q1, target_q2 = learner_state.critic_state.apply_fn(
            {"params": learner_state.target_critic_params},
            batch.next_model_states,
            next_joint_actions,
        )
        alpha = jnp.exp(learner_state.alpha_state.params["log_alpha"])

        focal_next_log_prob = next_log_probs[:, agent_id]
        td_target = batch.rewards + (
            config.gamma
            * (1.0 - batch.dones)
            * (
                jnp.minimum(target_q1, target_q2)
                - alpha * focal_next_log_prob
            )
        )
        td_target = jax.lax.stop_gradient(td_target)

        q1, q2 = learner_state.critic_state.apply_fn(
            {"params": learner_state.critic_state.params},
            batch.model_states,
            batch.actions,
        )
        q1_error = q1 - td_target
        q2_error = q2 - td_target
        q1_loss = jnp.mean(jnp.square(q1_error))
        q2_loss = jnp.mean(jnp.square(q2_error))
        return {
            "fixed_critic_loss": q1_loss + q2_loss,
            "fixed_q1_loss": q1_loss,
            "fixed_q2_loss": q2_loss,
            "fixed_td_abs_mean": 0.5 * (
                jnp.mean(jnp.abs(q1_error))
                + jnp.mean(jnp.abs(q2_error))
            ),
            "fixed_q1_mean": jnp.mean(q1),
            "fixed_q2_mean": jnp.mean(q2),
            "fixed_target_q_mean": jnp.mean(td_target),
            "fixed_alpha": alpha,
        }

    return jax.jit(evaluate) if jit else evaluate
